### ISSUE TITLE
Nullable shortnames in commands

### ISSUE THREAD

**Issue by gnkz** [opulencephp/console#1]
According to the constructor of the **Opulence\Console\Requests\Option** class, short names can be nullable, but when the **Opulence\Console\Commands\Compilers\Compiller** class checks if the short name is set it uses the method optionIsSet from **Opulence\Console\Requests\IRequest** wich expect a string.

This is giving me troubles because i'm forced to define a short name.

The error:

`Argument 1 passed to Opulence\Console\Requests\Request::optionIsSet() must be of the type string, null given, called in /app/vendor/opulence/opulence/src/Opulence/Console/Commands/Compilers/Compiler.php on line 87`

My development environment:

OS: Ubuntu 14.04
PHP Version: 7.0.14-2+deb.sury.org~trusty+1

**Comment by opulencephp** [comment]
Thanks for catching this.  I'll get a fix out shortly!

**Comment by opulencephp** [comment]
OK, the fix is out.  Let me know if it continues to be a problem.

**Comment by gnkz** [comment]
Working as expected now, thanks!
